Typo2/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Typo.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        public ActionResult TypeRacer()
        {
            //Checks if the user has a license
            if (Request.Cookies["LicenseInfo"] != null)
            {
                return View();
            }
            else
            {
                //Otherwise return the home page
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Typo2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Typo.Logic.Services;
using Typo.Model.Models;

namespace Typo2.Controllers
{
    public class HomeController : Controller
    {
        private readonly AdminService _adminServices;
        private readonly AccountService _accountServices;
     
        public HomeController()
        {
            //Getting the accountservices
            _accountServices = new AccountService();
            //Getting the adminservices
            _adminServices = new AdminService();
        }

        [HttpPost]
        public ActionResult Index(Account account)
        {
            //Logging the user in
            Account Account;
            try { Account = _accountServices.Login(account.MailUser, account.Password); }
            catch (Exception e)
            {
                ViewData["Message"] = e.Message;
                return View();
            }
            //Making the cookies of that particular account
            if (Account != null)
            {
                HttpCookie cookie = new HttpCookie("UserInfo");
                string userJson = JsonConvert.SerializeObject(Account);
                cookie.Value = userJson;
                //cookie["Password"] = account.password;
                cookie.Expires.AddDays(1);
                Response.Cookies.Add(cookie);
                return RedirectToAction("Index", "Home");
            }
            return View();

        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult purchase()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult Games()
        {
            return View();
        }
        public ActionResult Admin()
        {
            //Getting access to the admin page if the admin INT == 1
            if (Request.Cookies["UserInfo"] != null)
            {
                Account user;
                user = JsonConvert.DeserializeObject<Account>(Request.Cookies["UserInfo"].Value);
                if (user.IsAdmin == 1)
                {
                    List<Account> listAccounts;
                    listAccounts = _adminServices.GetAllAccounts();
                    return View(listAccounts);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Admin(Account account)
        {
            //Getting access to the DeleteAccount function inside adminServices
            try
            {
                _adminServices.DeleteAccount(account.UserId);

                return RedirectToAction("Admin", "Home");

            }
            catch (Exception e)
            {
                return Json("error");
            }
           
        }
        public ActionResult Docent()
        {
            //Loggin the teacher in
            Account user;
            if (Request.Cookies["UserInfo"] != null)
            {
                user = JsonConvert.DeserializeObject<Account>(Request.Cookies["UserInfo"].Value);
                if (user.IsDocent == 1)
                {
                    return View();
                }
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Typo2/Controllers/LicenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Typo.Logic.Services;
using Typo.Model.Models;

namespace Typo2.Controllers
{
    public class LicenseController : Controller
    {
        private readonly KeyService _keyServices;
        public LicenseController()
        {
            _keyServices = new KeyService();
        }
        // GET: License
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GenerateKey(Key key)
        {
            //Generating key
            Account user;
            if (Request.Cookies["UserInfo"] != null)
            { 
                user = JsonConvert.DeserializeObject<Account>(Request.Cookies["UserInfo"].Value);
                _keyServices.GenerateKey(key.LicenseKey, user.UserId);
            }
            return RedirectToAction("Index", "Home");
        }
        public ActionResult CheckLicense()
        {
            //Checking the license
            Account user;
            Key key;
            key = null;
            if (Request.Cookies["UserInfo"] != null)
            {
                user = JsonConvert.DeserializeObject<Account>(Request.Cookies["UserInfo"].Value);
                key = _keyServices.CheckLicense(user.UserId);
                if (key != null)
                {
                    HttpCookie cookie = new HttpCookie("LicenseInfo");
                    string userJson = JsonConvert.SerializeObject(key);
                    cookie.Value = userJson;
                    //cookie["Password"] = account.password;
                    cookie.Expires.AddDays(1);
                    Response.Cookies.Add(cookie);
                    return RedirectToAction("Typeracer", "Game");
                }
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Typo2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Typo2/Views/Home/Admin.cshtml
@using Typo.Model.Models
@model List<Typo.Model.Models.Account>
@{
    ViewBag.Title = "Admin";
}

<head>
    <link rel="stylesheet" href="~/styles/admin.css">
</head>

<a href='@Url.Action("Index", "Home")'><button id="button2">Ga terug naar de hoofdpagina</button></a>
<h1>Admin</h1>

<div class="admin-container">
    <div class="admin-table">
        <table>
            <tr class="table-names">
                <th>User ID</th>
                <th>E-mail</th>
                <th>Password</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Birthdate</th>
                <th>Teacher</th>
                <th>Admin</th>
                <th>Delete</th>
            </tr>
            @foreach (var d in Model)
            {
                <form id="deleteAccount" method="post">
                    <tr id="userRow-@d.UserId">
                        <input asp-for="UserId" name="UserId" type="number" value="@d.UserId" hidden />
                        <td>@d.UserId.</td>
                        <td>@d.MailUser</td>
                        <td>@d.Password</td>
                        <td>@d.FirstName</td>
                        <td>@d.LastName</td>
                        <td>@d.BirthDate</td>
                        <td class="table-spacing">@d.IsDocent</td>
                        <td class="table-spacing">@d.IsAdmin</td>
                        @*<td>
                                <button onclick="DeleteRow('@Model[i].UserId')" id="delete-@Model[i].UserId" type="submit">DELETE!</button>
                            </td>*@
                        <td>
                            <button id="delete-@d.UserId" type="submit" class="btn btn-danger">Delete</button>
                        </td>
                    </tr>
                </form>
            }
        </table>
    </div>
</div>

Typo2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Fontys Hogescholen<br />
    Rachelsmolen, 5612 MA Eindhoven<br />
    <abbr title="Phone">P:</abbr>
    088 508 0000
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Typo@fontys.nl">Typo@fontys.nl</a><br />
    <strong>Marketing:</strong> <a href="mailto:Typo@marketing.nl">Typo@marketing.nl</a>
</address>
<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2486.330293480661!2d5.479793915938489!3d51.45209192256635!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c6d92199730073%3A0x1c98f3a0d8ee087b!2sFontys%20Hogescholen!5e0!3m2!1snl!2snl!4v1574208641587!5m2!1snl!2snl" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
</div>

Typo2/Views/Home/Index.cshtml
@using System.ComponentModel
@using Newtonsoft.Json
@using Typo.Model.Models
@model Typo.Model.Models.Account
@{
    ViewBag.Title = "Home Page";
}
@{
    string Welcome = "welcome, ";
    string firstName = "";
    string lastName = "";
    var adminLogin = 0;
    var licensekey = "";
    if (Request.Cookies["UserInfo"] != null)
    {
        var user = JsonConvert.DeserializeObject<Account>(Request.Cookies["UserInfo"].Value);
        firstName = user.FirstName;
        adminLogin = user.IsAdmin;
    }
}



<head>
    @*<title>TYPO</title>
        <link rel="stylesheet" href="/styles/index.css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500&display=swap" rel="stylesheet">
        <script src="/Scripts/jquery-3.3.1.min.js"></script>
        <script src="/Scripts/main.js"></script>*@
    <link rel="stylesheet" href="/styles/index.css">
</head>

<nav>
    <div id="sidebar">
        <a href='@Url.Action("Index", "Home")'><img id="logo" src="~/images/logo.png" /></a>

        <ul>
            <div class="logged-user">
                <li>
                    @if (firstName != "")
                    {<h1 class="welcome-font"> Welcome, @firstName</h1>}
                </li>
            </div>
            <li><a href="#about">Over ons</a></li>
            <li><a href="#features">Features</a></li>
            <li><a href="#benefits">Voordelen</a></li>
            <li><a href="#contact">Contact</a></li>
            <li>@Html.ActionLink("Games", "Games", "Home")</li>
            @if (adminLogin != 0)
            {
                <li><a class="login-form1">@Html.ActionLink("ADMIN!", "Admin", "Home")</a></li>

            }
            else
            {
                <li><a class="login-form1">@Html.ActionLink("Koop nu", "Purchase", "Home")</a></li>
            }

            @if (firstName == "")
            {
                <li><a href="#" id="login">Account</a></li>
            }
            else
            {
                <li><a class="login-form1">@Html.ActionLink("Check je licentie", "CheckLicense", "License")</a></li>
                <li><a class="login-form1">@Html.ActionLink("Log uit", "LogOut", "Account")</a></li>
            }
            <div class="login-form">
                <form id="login-form-id" method="post">
                    <label>E-mail</label>
                    <div>
                        <input name="MailUser" type="text" placeholder="Vul e-mail adres in" required />
                    </div>
                    <label>Wachtwoord</label>
                    <div>
                        <input name="Password" type="password" placeholder="Vul wachtword in" required />
                    </div>
                    <div>
                        <input type="submit" value="Log in" />
                    </div>
                    <div class="register">
                        @*<a href="register.cshtml">Geen account? Registreer hier</a>*@
                        <a> @Html.ActionLink("Geen account? Registreer hier", "Register", "Account")</a>
                    </div>
                </form>
            </div>
        </ul>
    <div id="sidebar-btn">
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
</nav>
<div class="header">
    <img class="header-logo" src="~/images/logo.png">
</div>

<div class="header-transition">
    <div class="transition-img-1">
        <div class="transition-img-container">
            <img class="transition-img" src="~/images/transition-image3.jpg">
        </div>
    </div>
    <div class="transition-img-2">
        <div class="transition-img-container">
            <img class="transition-img" src="~/images/transition-image2.jpg">
        </div>
    </div>
    <div class="transition-img-3">
        <div class="transition-img-container">
            <img class="transition-img" src="~/images/transition-image1.jpg">
        </div>
    </div>
</div>

<div id="about" class="about-container">
    <div class="about-line"></div>
    <div class="about-h2">
        <h2>OVER ONS</h2>
    </div>
    <div class="about-h1">
        <h1>Wij zijn TYPO – een bedrijf dat typ cursussen ontwikkelt, gericht op het maken van educatieve videogames  voor zowel professioneel als privégebruik.</h1>
    </div>
    <div class="about-text1">
        <p>Onze games gaan zowel kinderen als volwassen de vaardigheid van blind typen leren, een noodzaak in de digitale samenleving van vandaag.</p>
    </div>
    <div class="about-text2">
        <p>Ons doel is om producten te hebben die geschikt zijn voor alle leeftijdsgroepen, waardoor leren een plezierige ervaring voor zowel u als uw kinderen wordt.</p>
    </div>
</div>

<div id="features" class="features-container">
    <div class="features-block">
        <h3>TYPO biedt een typ cursus aan voor jong en oud.</h3>
    </div>
    <div class="features-img-container1">
        <img class="features-img" src="~/images/adjust.png">
    </div>
    <div class="features-text1">
        <h1>01.</h1>
        <h2>niveaus</h2>
        <p>Nog nooit leren typen?<br> Geen probleem! In onze games heb je keuze uit meerdere moeilijkheden en typsnelheden, zo kun je een passend niveau uitkiezen.</p>
    </div>
    <div class="features-img-container2">
        <img class="features-img" src="~/images/choices.png">
    </div>
    <div class="features-text2">
        <h1>02.</h1>
        <h2>varianten</h2>
        <p>Voor ons is het belangrijk dat onze spellen uitdaging en plezier voor alle leeftijden bieden. Probeer het spel uit dat het beste bij je past en leer zo gemakkelijk blind te typen.</p>
    </div>
</div>

<div id="benefits" class="benefits-container">
    <div class="benefits-line"></div>
    <div class="benefits-h2">
        <h2>VOORDELEN</h2>
    </div>
    <div class="benefits-h1">
        <h1>Wat zijn de voordelen van TYPO?</h1>
    </div>
    <div class="benefits-under">
        <p>Bij TYPO hebben wij een missie en deze begint bij onze drie I's:<br><br><b>Innovatief</b>, de beste op ons gebied. <br><b>Interactief</b>, gemakkelijk en voor iedereen. <br><b>Ingenieus</b>, voor jong en oud.</p>
    </div>
    <div class="benefits-box1">
        <h1>highscore</h1>
        <p>Houd je voortgang bij met ons score systeem en blijf jezelf verbeteren.</p>
    </div>
    <div class="benefits-box2">
        <h1>multiplayer</h1>
        <p>Neem het op tegen je vrienden en familie in multiplayer en wordt een winnaar.</p>
    </div>
    <div class="benefits-box3">
        <h1>overzicht</h1>
        <p>Ben je een ouder of docent? Ook met TYPO kun je de score van je klas of kind makkelijk bijhouden.</p>
    </div>
    <div class="benefits-box4">
        <h1>1 account, 3 spellen</h1>
        <p>Met een TYPO account kun je onze spellen op elke computer spelen en neem je je voortang met je mee.</p>
    </div>
    <div class="benefits-box5">
        <h1>TYPO raceset</h1>
        <p>Wordt een échte racer met de TYPO raceset  en laat iedereen zien hoe goed jij typt.</p>
    </div>
</div>

<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2486.330293480661!2d5.479793915938489!3d51.45209192256635!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c6d92199730073%3A0x1c98f3a0d8ee087b!2sFontys%20Hogescholen!5e0!3m2!1snl!2snl!4v1574208641587!5m2!1snl!2snl" allowfullscreen=""></iframe>
</div>

<div id="contact" class="contact-container">
    <div class="contact-line"></div>
    <div class="contact-h2">
        <h2>CONTACT</h2>
    </div>
    <div class="contact-h1">
        <h1>Neem contact met ons op.</h1>
    </div>
    <div class="contact-text">
        <p>
            Fontys Hogescholen<br>
            Rachelsmolen, 5612 MA Eindhoven<br><br>

            <a href="tel:088-508-0000">T. 088-508-0000</a><br>

            <a href="mailto:Typo@fontys.nl">Typomailservice@gmail.nl</a><br><br><br><br><br><br>
            Alle velden zijn verplicht.
        </p>
    </div>

    <form>
        <label for="name">Naam</label>
        <input type="text2" id="name" name="name" placeholder="Uw naam" required>
        <label for="email">E-mail</label>
        <input type="text2" id="email" name="email" placeholder="Uw e-mailadres" required>
        <label for="subject">Onderwerp</label>
        <input type="text2" id="subject" name="subject" placeholder="Uw onderwerp" required>
        <label for="message">Bericht</label>
        <textarea id="message" class="contact-message" name="message" placeholder="Uw bericht" style="height:200px"></textarea>
        <input type="submit2" value="Verzenden" required>
    </form>
</div>

<div class="footer">
    © 2019 TYPO
</div>

Typo2/Views/Home/docent.cshtml
@{
    ViewBag.Title = "docent";
}

<h2>docent</h2>

Typo2/Views/Home/games.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>TYPO</title>
    <link rel="stylesheet" href="~/styles/games.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500&display=swap" rel="stylesheet">
    <script src="addons/jquery/jquery-3.4.1.min.js"></script>
    <script src="scripts/main.js"></script>
</head>

<body>
    <a href='@Url.Action("Index", "Home")'><button id="button2">Ga terug naar de hoofdpagina</button></a>
    <div class="games-container">
    <div class="header-container">
        <h2>Account</h2>
        <h1>Games</h1>
        <hr class="heading-line">
    </div>
    <div class="product-container">
        <div class="product">
            <div class="game-alignment">
                <h1 style="color:#0d171a;">GAME 1</h1>
                <hr class="game-line">
                <h5></p>[beschrijving hier]</h5>
            </div>
            <img class="game-image" src="~/images/game1.jpg">
            <button class="btn btn-info" id="button" type="submit">Download</button>
        </div>
        <div class="product">
            <div class="game-alignment">
                <h1 style="color:#0d171a;">GAME 2</h1>
                <hr class="game-line">
                <h5></p>[beschrijving hier]</h5>
            </div>
            <img class="game-image" src="~/images/game2.jpg">
            <button class="btn btn-info" id="button" type="submit">Download</button>
        </div>
        <div class="product">
            <div class="game-alignment">
                <h1 style="color:#0d171a;">GAME 3</h1>
                <hr class="game-line">
                <h5></p>[beschrijving hier]</h5>
            </div>
            <img class="game-image" src="~/images/game3.jpg">
            <button class="btn btn-info" id="button" type="submit">Download</button>
        </div>
        </div>
    </form>
</div>
    <div class="footer">
        © 2019 TYPO
    </div>
</body>
</html>