Typo/Models/ErrorViewModel.cs
using System;

namespace Typo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Typo/Models/Score.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Typo.Models
{
    public class Score
    {
        public static Score Scores { get; set; }
        public int scoreId { get; set; }
        public string score { get; set; }
    }
}

Typo/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace Typo.Controllers
{
    public class AccountController : Controller
    {
        //private readonly AccountService _accountServices;


        //public AccountController()
        //{
        //    _accountServices = new AccountService();
        //}

        public IActionResult Register()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult Register(Account accounts)
        //{
            //var query = "INSERT INTO Account(username, password) VALUES('{0}', '{1}')";
            //var queryFull = string.Format(query, accounts.username, accounts.password);
            //var sc = new SqlConnection(_connectionString);
            //sc.Open();
            //using (SqlCommand cmd = new SqlCommand(queryFull, sc))
            //{
            //    try
            //    {
            //        cmd.ExecuteNonQuery();
            //        sc.Close();
            //    }
            //    catch
            //    {

            //        sc.Close();
            //    }
            //}
            //// hoi
            //return RedirectToAction("Register", "Account");
        //}

        //[HttpPost]
        //public ActionResult Login(Account account)
        //{
        //    _accountServices.Login(account.username, account.password);

        //    return RedirectToAction("Index", "Home");
        //}

        //public IActionResult LogOut()
        //{
        //    if (Account.Accounts != null)
        //    {
        //        Account.Accounts = null;
        //    }

        //    return RedirectToAction("Login", "Account");
        //}
    }
}

Typo/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Typo.Controllers
{
    public class GameController : Controller
    {
        public IActionResult TypeRacer()
        {
            return View();
        }
    }
}

Typo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
//using Typo.Model.Models;

namespace Typo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return null;
        }
    }
}

Typo/Controllers/ScoreController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Logic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Typo.Controllers;
using Typo.Models;


namespace Typo.Controllers
{
    public class ScoreController : Controller
    {
        readonly string _connectionString;
        public ScoreController(IConfiguration config)
        {
            _connectionString = config.GetSection("Connection")["MSSQL"];
        }

        
        public IActionResult ScoreCheck()
        {
            return View();
        }

        public IActionResult ScoreInput()
        {
            return View();
        }



        [HttpPost]
        public IActionResult ScoreInput(Score scores)
        {
            var query = "INSERT INTO ScoreId1(score) VALUES('{0}')";
            var queryFull = string.Format(query, scores.score);
            var sc = new SqlConnection(_connectionString);
            sc.Open();
            using (SqlCommand cmd = new SqlCommand(queryFull, sc))
            {
                try
                {
                    cmd.ExecuteNonQuery();
                    sc.Close();
                }
                catch
                {

                    sc.Close();
                }
            }
            return RedirectToAction("ScoreInput", "Score");
        }







        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ScoreCheck(Score score)
        {
            var IdUser = ScoreResult(score);
            if (IdUser != null)
            {

                
                return RedirectToAction("ScoreCheck", "Score");

            }
            return View();
        }

        private Score ScoreResult(Score score)
        {
            Score scores = null;
            var query = "SELECT * FROM ScoreId";

            
            query += score;
            query += " WHERE score = '{0}'";
            var queryFull = string.Format(query, scores.score);
            var sc = new SqlConnection(_connectionString);
            sc.Open();
            using (SqlCommand cmd = new SqlCommand(queryFull, sc))
            {
                SqlDataReader reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    scores = new Score()
                    {
                        scoreId = reader.GetInt32(0),
                        score = reader.GetString(1)
                    };
                }
            }
            return scores;
        }




        /*
        public IActionResult LogOut()
        {
            if (Account.Accounts != null)
            {
                Account.Accounts = null;
            }

            return RedirectToAction("Login", "Account");
        }
        */
    
    }
}

Typo/Views/Game/TypeRacer.cshtml
@{
    ViewData["Title"] = "TypeRacer";
}

<h2>TypeRacer</h2>

Typo/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.test</p>

Typo/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Fontys Hogescholen<br />
    Rachelsmolen, 5612 MA Eindhoven<br />
    <abbr title="Phone">P:</abbr>
    088 508 0000
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Typo@fontys.nl">Typo@fontys.nl</a><br />
    <strong>Marketing:</strong> <a href="mailto:Typo@marketing.nl">Typo@marketing.nl</a>
</address>
<div class="map">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2486.330293480661!2d5.479793915938489!3d51.45209192256635!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c6d92199730073%3A0x1c98f3a0d8ee087b!2sFontys%20Hogescholen!5e0!3m2!1snl!2snl!4v1574208641587!5m2!1snl!2snl" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
</div>

Typo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="jumbotron Header">
    <h1>Typo!</h1>
</div>
<div class="center">
    <button onclick="location.href='@Url.Action("TypeRacer", "Game")'" type="button" class="btn btn-danger">Typeracer!</button>
    <button type="button" class="btn btn-primary">Game #2</button>
    <button type="button" class="btn btn-warning">Game #3</button>
    <button type="button" class="btn btn-success">Game #4</button>
</div>

Typo/Views/Score/ScoreCheck.cshtml
@model Typo.Models.Score
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<div class="page-header">
    <h1>Score <small>to check a score</small></h1>
</div>
<div class="container">
    <div class="row" id="test">
        <div class="col-sm-6">
            <div class="col-lg-12">
                <form method="post">
                    <div class="well">
                        <div class="form-group">
                            @*<h3 style="line-height: 20%;"><i class="fa fa-home fa-1x" style="line-height: 6%; color: #339966"></i> FirstName:</h3>*@
                            <label asp-for="score"></label>
                            <input asp-for="score" class="form-control" placeholder="Fill ID" data-val="true" />
                            <span asp-validation-for="score" class="text-danger"></span>
                        </div>
                        <button class="btn btn-default" type="submit">ScoreCheck</button>
                    </div>
                </form>
                @ViewData["Message"]
            </div>
        </div>
    </div>
</div> 

Typo/Views/Score/ScoreInput.cshtml
@model Typo.Models.Score
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<div class="page-header">
    <h1>Score <small>to input score in database</small></h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="col-lg-12">
                <form method="post">
                    <div class="well">
                        <div class="form-group">
                            @* <h3 style="line-height: 20%;"><i class="fa fa-home fa-1x" style="line-height: 6%; color: #339966"></i> FirstName:</h3> *@
                            <label asp-for="score"></label>
                            <input asp-for="score" class="form-control" placeholder="Fill score" data-val="true" />
                            <span asp-validation-for="score" class="text-danger"></span>
                        </div>
                        <button class="btn btn-default" type="submit">ScoreInput</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Typo/Views/Shared/_Layout.cshtml
//@using Typo.Model.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Typo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Typo</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li>
                        @{
                            if (Account.Accounts == null)
                            {
                                <a onclick="example_ajax_request()" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            }
                            else
                            {
                                <a onclick="example_ajax_request()" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            }

                        }

                    </li>

                    <li>
                        @{
                            if (Account.Accounts == null)
                            {
                                <a asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            }
                        }

                    </li>
                </ul>
            </div>
            
            
        </div>
        @if (Account.Accounts != null) { 
            <div class="logging"> 
                <span>Logged in as @TempData["Message"]</span>
                @Account.Accounts.username
            </div>
        }
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Typo</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>